version: "3"
services:
  database:
    image: mariadb:latest 
    container_name: cryptopills_db
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cryptopills_db
    ports:
      - 3306:3306
    volumes:
      - ../mariadb/init:/docker-entrypoint-initdb.d
      - mariadb-data:/var/lib/mysql

  grafana:
    image: grafana/grafana
    container_name: cryptopills_grafana
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3001
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana
  
  webserver:
    image: masellinator/cryptopills_webserver
    container_name: cryptopills_webserver
    restart: always
    ports:
      - 8082:8082

volumes:
  mariadb-data: {}
  grafana-data: {}

