{
 "title": "liquity-usd",
 "time": { "from": "2021-05-18T20:46:08.000Z", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Icon",
   "type": "text",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>liquity-usd<h1>\n<img src=https://assets.coingecko.com/coins/images/14666/large/Group_3.png?1617631327)/>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Graph",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT last_updated AS time, current_price AS price\nFROM Crypto_Price\nWHERE id_crypto='liquity-usd'"
    }
   ]
  },
  {
   "title": "Current Price",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT last_updated AS time, current_price\nFROM Crypto_Price\nWHERE id_crypto='liquity-usd'"
    }
   ]
  },
  {
   "title": "MARKET CAP RANK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,id_crypto AS metric, market_cap_rank\nFROM Crypto_Market\nWHERE id_crypto='liquity-usd'"
    }
   ]
  },
  {
   "title": "MARKET CAP CHANGE % 24H",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "displayType": "Regular",
     "rawSql": "SELECT NOW() AS time,id_crypto AS metric, market_cap_change_percentage_24h\nFROM Crypto_Market\nWHERE id_crypto='liquity-usd'",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "MARKET CAP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() AS time,id_crypto AS metric, market_cap\nFROM Crypto_Market\nWHERE id_crypto='liquity-usd'"
    }
   ]
  },
  {
   "title": "ALL INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Homepage",
     "type": "dashlist",
     "gridPos": { "h": 4, "w": 11, "x": 6, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    }
   ]
  }
 ]
}